SELECT TUM.USER_NAME,
	TPM.PRODUCT_NAME ,
	A.LAST_TRANSACTION_DATE,
	ISNULL(B.AMOUNT_PAID,0) AMOUNT_PAID,
	C.ORDERED_QUANTITY,
	((C.ORDERED_QUANTITY*TPM.COST_PER_ITEM) - ISNULL(B.AMOUNT_PAID,0)) BALANCE
FROM
		(
			SELECT USER_ID,
				PRODUCT_ID,
				MAX(TRANSACTION_DATE) LAST_TRANSACTION_DATE
			FROM T_TRANSACTIONS
			GROUP BY USER_ID, PRODUCT_ID
		) A
LEFT JOIN 
		(
			SELECT USER_ID,
				PRODUCT_ID, 
				TRANSACTION_AMOUNT AMOUNT_PAID
			FROM T_TRANSACTIONS
			WHERE TRANSACTION_TYPE = 'PAYMENT'
		) B ON A.USER_ID = B.USER_ID AND A.PRODUCT_ID = B.PRODUCT_ID
LEFT JOIN 
		(
			SELECT USER_ID,
					PRODUCT_ID, 
					SUM(TRANSACTION_AMOUNT) ORDERED_QUANTITY
			FROM T_TRANSACTIONS	
			WHERE TRANSACTION_TYPE = 'ORDER'
			GROUP BY USER_ID, PRODUCT_ID
		)C 
ON A.USER_ID = C.USER_ID AND A.PRODUCT_ID = C.PRODUCT_ID
LEFT JOIN
   T_PRODUCT_MASTERS TPM ON TPM.PRODUCT_ID=A.PRODUCT_ID
LEFT JOIN
   T_USER_MASTERS TUM ON TUM.USER_ID=A.USER_ID
ORDER BY TUM.USER_NAME