
/*1ST*/
SELECT 
       D.DeptName,
	   GENDER,
	   COUNT(ID) AS NO_OF_EMPLOYEE
	   FROM EMPLOYEE
	   LEFT JOIN
	   DEPARTMENT D
	   ON EMPLOYEE.DEPTID=D.DeptID
GROUP BY D.DeptName,GENDER
ORDER BY DeptName
/*2ND QUERY*/
SELECT A.DEPTNAME,A.NO_OF_EMPLOYEE,
       A.TOTAL_SALARY,
	   B.HIGHEST_GROSS
	   FROM
(
		SELECT EMPLOYEE.DeptID,
		       DEPARTMENT.DeptName,
			   COUNT(ID) AS NO_OF_EMPLOYEE,
			   MAX(EMPLOYEE.BASIC) AS TOTAL_SALARY
		FROM EMPLOYEE 
		INNER JOIN
		DEPARTMENT ON
		EMPLOYEE.DEPTID=DEPARTMENT.DeptID
		GROUP BY EMPLOYEE.DEPTID,DeptName
		)A
LEFT JOIN
(
		SELECT MAX(BASIC+HR+DA+TAX) AS HIGHEST_GROSS,
			   DEPTID
		FROM EMPLOYEE
		GROUP BY DEPTID
)B ON A.DEPTID=B.DEPTID

/*5TH QUERY*/
SELECT NAME,
       ID
	   FROM EMPLOYEE 
	   WHERE BASIC=(
SELECT MAX(BASIC)
FROM EMPLOYEE 
WHERE BASIC
NOT IN (
         SELECT MAX(BASIC)
       FROM EMPLOYEE
	   )
	   )

/*7TH QUERY*/
SELECT NAME,
       DEPARTMENT.DeptName
FROM EMPLOYEE
INNER JOIN
DEPARTMENT
ON EMPLOYEE.ID=DEPARTMENT.DeptHeadID 

/*3RD QUERY*/
SELECT NAME,
       DEPTID,
	   BASIC+HR+DA+TAX AS HIGHEST_GROSS_SALARY 
FROM EMPLOYEE WHERE (BASIC+HR+DA+TAX) IN 
(SELECT 
	   MAX(BASIC+HR+DA+TAX) AS HIGHEST 
FROM EMPLOYEE
GROUP BY DEPTID
)
GROUP BY DEPTID,NAME,BASIC,HR,TAX,DA

/*6TH*/
SELECT DEPARTMENT.DeptName,
       COUNT(EMPLOYEE.DEPTID) AS NO_OF_EMPLOYEE
FROM EMPLOYEE
INNER JOIN
DEPARTMENT ON EMPLOYEE.DEPTID=DEPARTMENT.DeptID
GROUP BY DEPARTMENT.DEPTID,DEPARTMENT.DeptName
HAVING COUNT(EMPLOYEE.DEPTID)>3

SELECT EMPLOYEE.NAME
FROM EMPLOYEEATTENDANCE
INNER JOIN
EMPLOYEE ON
EMPLOYEEATTENDANCE.EMPID=EMPLOYEE.ID
GROUP BY EMPID,NAME
HAVING SUM(WORKING_DAYS)-SUM(PRESENTDAYS)=0


	  

       
    